### ISSUE TITLE
в функциях при формировании строки подключения dblink использует только dbname

### ISSUE THREAD

**Issue by triwada** [zubkov-andrei/pg_profile#1]
Если кластер PostgreSQL прослушивает нестандартный tcp-порт (5432), то функция snapshot() завершается ошибкой вида

postgres=# SELECT profile.snapshot();
ERROR:  could not establish connection
DETAIL:  FATAL:  database "zabbix" does not exist
 
CONTEXT:  SQL statement "INSERT INTO temp_stat_user_tables
      SELECT s_id,r_result.datid,t.*
      FROM dblink('dbname='||r_result.datname, 'select *,pg_relation_size(relid) relsize,0 relsize_diff from pg_catalog.pg_stat_user_tables')
      AS t (
...

Проблема в том, что в функции при формировании строки подключения используется только dbname

postgres=# SELECT dblink_connect('dbname=zabbix');
ERROR:  could not establish connection
DETAIL:  FATAL:  database "zabbix" does not exist
 
postgres=# SELECT dblink_connect('dbname=zabbix port=5463');
 dblink_connect
 OK
(1 row)

**Comment by zubkov-andrei** [comment]
Отличное замечание. В следующем релизе точно исправлю. В виду критической значимости, легкости исправления и тестирования, может даже выпущу апдейт до выхода релиза.

**Comment by zubkov-andrei** [comment]
Попробуйте обновиться на 0.0.4a, теперь должно работать на любом порту.

**Comment by triwada** [comment]
Спасибо, обновление 0.0.4a решило проблему
