### ISSUE TITLE
Wait Events

### ISSUE THREAD

**Issue by hvanderland** [zubkov-andrei/pg_profile#10]
Andrei, 

Thank you for this excellent package. It's very useful.  
Coming from an Oracle background, this is a good replacement for AWR.

One thing I'm missing is some wait event tracking.
Would it make sense to add top sql tracing based on wait events from the pg_stat_activity table?

Regards
Harry.

**Comment by zubkov-andrei** [comment]
Hi, Harry!

I'm glad you found useful _pg_profile_ extension, it was developed exactly as replacement for Oracle AWR.

What can I say about wait event tracking? It is very demanded feature, but for now there isn't any community accepted approach to solve this problem. _pg_stat_activity_ is a nearly real-time view - it shows you only wait events, that sessions is waiting right now, thus we don't know how long sessions was waiting for this particular event, and what events and for how long they was waiting in the past. Right now the only non-invasive approach is periodic sampling of wait events, but this sampling must be much more frequent than cumulative statistics sampling of _pg_profile_.
Our team is developing this approach as an extension [pg_wait_sampling](https://github.com/postgrespro/pg_wait_sampling) and as a part of _pgpro_stats_ extension (supported by enterprise version of _pg_profile_) of our enterprise PostgresPro fork. It's documentation is available [here](https://postgrespro.com/docs/enterprise/12/pgpro-stats).

_pg_wait_sampling_ is not supported by _pg_profile_ right now, but I think it will be supported in near feature.

**Comment by hvanderland** [comment]
Thank you for your responds and interesting to read about the PostgresPro edition.

The problem is that we’re running on AWS RDS Postgresql, which does not allow to add third party extensions to the database.
I am able to add PG_profile in this environment as a set of procedures into a separate schema. This works as expected even not created as an extension.

Sampling the pg_stat_actuvity table every second seems to be the only option. We’ll have to check how much overhead this has on the database.

Regards
Harry Vanderland.

**Comment by zubkov-andrei** [comment]
Finally pg_wait_sampling support is added to pg_profile in version 4.0. Right now it shows only cluster-wide wait statistics, but this is better than nothing.
