### ISSUE TITLE
400MB html report

### ISSUE THREAD

**Issue by cwang9208** [zubkov-andrei/pg_profile#101]
Hi,

I just found that the generated report can be as large as 400+MB using the latest pg_profile-4.6. It's even difficult to open that html in browser. I guess there should be some bug. It's quite easy to reproduce: on a fresh Ubuntu 22.04 system with PostgreSQL-14 installed using apt-get. Then just install the pg_profile-4.6 and take 2 samples and generate a report.

Could anyone help look into this problem?

**Comment by cwang9208** [comment]
Besides, the generated report is not readable. It only has the following content:
```
Postgres profile report

(1 row)
```

**Comment by zubkov-andrei** [comment]
Hi!

Did you use all psql flags noted in [docs](https://github.com/zubkov-andrei/pg_profile/blob/master/doc/pg_profile.md#reports) while building a report? Those '-Aqt' are required to exclude psql output format.

**Comment by cwang9208** [comment]
@zubkov-andrei '-Aqt' fixes the problem. Thanks.
