### ISSUE TITLE
StartID в шапке отчета не попадает в отчет.

### ISSUE THREAD

**Issue by Guzya** [zubkov-andrei/pg_profile#17]
Здравствуйте!
В шапке отчета:
Postgres profile report (StartID: 2094, EndID: 2100)
Смотрю раздел Database statistics -> Growth и сравниваю с прямой выборкой из таблицы  sample_stat_database -> sum(datsize_delta)

select sample_id,datsize_delta from profile.sample_stat_database where sample_id between 2094 and 2100 and datname='postgres' order by sample_id;

и получаю расхождение на величину в sample_id=2094.
Получается StartID: 2094  не попадает в подсчет.

**Comment by zubkov-andrei** [comment]
Большое спасибо за поиск ошибок в модуле. Это очень нужно. Но в данном случае всё работает как надо. Дело в том, что в снимок с номером 2095 попадают инкременты статистик, накопившиеся с предыдущего снимка, т.е. с момента снимка 2094.
Таким образом, в рассчете приращений статистик с 2094 по 2100 участвуют снимки с 2094+1 по 2100.
