### ISSUE TITLE
Одно и тоже значение SeqBytes в дифференциальном отчёте.

### ISSUE THREAD

**Issue by D0KX** [zubkov-andrei/pg_profile#18]
Добрый день.
В таблице "Top tables by estimated sequentially scanned volume" получаю одни и те же значения ~SeqBytes за сравниваемые периоды, хотя SeqScan отличается. 
Насколько я понимаю данные должны так же показывать за период.
pg_profile version 0.3.2

**Comment by zubkov-andrei** [comment]
Добрый день!
14 мая вышел хотфикс этой баги в версии 0.3.3. Попробуйте обновиться.
