### ISSUE TITLE
Is it possible use on replica?

### ISSUE THREAD

**Issue by 4815162342lost** [zubkov-andrei/pg_profile#19]
Hello, i have a master database and replica database (slave, read-only).

I can not run pg_profile on replica:
```
postgres=# SELECT profiler.take_sample();
                                             take_sample                                             
-----------------------------------------------------------------------------------------------------
 (local,"cannot execute UPDATE in a read-only transaction                                           +
 SQL statement ""UPDATE servers SET last_sample_id = last_sample_id + 1 WHERE server_id = sserver_id+
       RETURNING last_sample_id""                                                                   +
 PL/pgSQL function take_sample(integer,boolean) line 80 at SQL statement                            +
 PL/pgSQL function take_sample_subset(integer,integer) line 27 at assignment                        +
 SQL function ""take_sample"" statement 1                                                           +
 ",00:00:00.05)
(1 строка)
```

What can we do? Or this tool usable only for non-replica databases?

**Comment by zubkov-andrei** [comment]
Hello!

Yes, it is little bit difficult. _pg_profile_ can't be used on hot standby environment directly, but you can configure _pg_profile_ data collection from your standby instance by some other cluster (muster will do also). You just need to define a new _server_ for your standby. See the last paragraph of [Concepts](https://github.com/zubkov-andrei/pg_profile/blob/master/doc/pg_profile.md#concepts) section.
Please refer to [Managing servers](https://github.com/zubkov-andrei/pg_profile/blob/master/doc/pg_profile.md#managing-servers) section of the doc to see server-management functions.
