### ISSUE TITLE
корректность расчета %total при выводе таблиц top sql by {executions, gets}

### ISSUE THREAD

**Issue by triwada** [zubkov-andrei/pg_profile#2]
При выводе в отчете таблиц  **_top sql by executions, top sql by gets_** сумма значений по столбцу %Total не равна 100%. 
Судя по коду функции top_exec_htbl общее число вызовов берется из разных таблиц. Значение %Total определяется как sum(st.calls/tot.calls)*100. Попробовал получить результат отношения по отдельности в рамках одного снимка. Есть расхождение.
postgres=# select sum(calls) from profile.snap_statements_total where snap_id=19;
 32362
postgres=# select sum(calls) from profile.v_snap_statements where snap_id=19;
 18593

Если это не ошибка, тогда, думаю, нужно в документации указать, что именно отображает столбец %Total в таблицах top sql by *.

**Comment by zubkov-andrei** [comment]
%Total показывает долю от общей нагрузки на кластер за указанный интервал.
В снимках хранятся только запросы, попадающие в топы по каким-либо категориям. То есть, не все.
Общая нагрузка для рассчетов %Total снимается в момент построения снимка и хранится в снимке в виде агрегатов по базам данных (показываются они в разделе отчета "Statements stats by database").
Значение %Total вычисляется как доля от общей нагрузки на кластер, т.е. от значений, указанных в последней строке раздела "Statements stats by database".
С %Total есть другая проблема - stat_statements.track=all, но про нее я рассказывал и в документации вроде написано. Вообще, документация, конечно, не очень детальная, но я и эту писал довольно долго. Руки дойдут, может дополню.

**Comment by triwada** [comment]
Теперь понятно.
