### ISSUE TITLE
Небольшие вопросы по внешнему виду отчета

### ISSUE THREAD

**Issue by antiorum** [zubkov-andrei/pg_profile#21]
Здравствуйте, Андрей. В первую очередь, хочется поблагодарить вас за этот проект. Есть несколько вопросов/пожеланий:
1. В Report interval: 2021-05-18 19:30:02 - 2021-05-19 19:30:01 - можно ли тут указать часовой пояс? 
2. Можно ли ограничить ширину таблицы с запросами (Complete list of SQL texts)? Сейчас она получается очень большой, сложно скопировать из нее запрос.
3. Возможно ли добавить подсветку (сделать другим цветом) строки таблиц, где значения превышают критические (например, время выполнения запроса > 5 секунд )?

**Comment by zubkov-andrei** [comment]
Здравствуйте!

1. Да, зону, конечно, можно указать. Отсутствие его там вызвано тем соображением, что администратор обычно работает с ограниченным набором серверов, или вообще с одним. Тогда он и так знает зону сервера, и в отчете это будет загромождать и без того длинные даты. Но, может, стоит зону все-таки включить. Если вам не трудно, опишите ситуацию, в которой вам оказалась нужна временная зона.
2. Думаю, это возможно, я попробую разные варианты. А какие у вас проблемы с копированием запроса? У меня firefox тройным щелчком легко выделяет всю ячейку таблицы.
3. С подсветкой проблем нет, это хорошая тема, что-то похожее у меня есть в списке дальнейших фич. Не реализовано пока из-за того, что надо подумать над механизмом выбора уровней, выделяющих объекты и запросы. Абсолютные значения вроде 5 секунд не видятся хорошим вариантом из-за того, что всё относительно - для каких-то запросов 5 секунд это очень плохо, а для каких-то очень хорошо. Думаю, тут будут какие-то квантили по историческим наблюдениям. Во всяком случае, пока мне это видится компромиссным вариантом. Но пока до опытов руки не дошли.

Если у вас будут предложения, которые стоит обсудить, думаю эту тему надо в [Discussions](https://github.com/zubkov-andrei/pg_profile/discussions) перенести.

**Comment by antiorum** [comment]
Ну второй и третий вопросы - это так, косметическое. Насчет часового пояса - кейс такой, что отчет смотрит не только администратор, но и другие люди (я), вполне возможно, что из другого региона.
