### ISSUE TITLE
SQL Query statistics

### ISSUE THREAD

**Issue by xiangma0510** [zubkov-andrei/pg_profile#24]
Through the change log updated,I can't found why the sections `Top SQL by elapsed time` and `Top SQL by planning time` not appeared in my report,My pgsql version is 13.4 and extension installed with pg_stat_statements,pg_profiile,pgplsql,pg_profile.

**Comment by zubkov-andrei** [comment]
Hi,

Plan timing statistics collection can cause performance issues, as it mentioned in the docs. There is a parameter named `pg_stat_statements.track_planning` which controls planning times collection. This parameter is disabled by default.
pg_profile won't show sections, based on plan timing data if this data is unavailable.

Please, enable `pg_stat_statements.track_planning` keeping in mind possible performance issues, and give me a feedback.
See [pg_stat_statements docs](https://www.postgresql.org/docs/13/pgstatstatements.html) for further reference.

**Comment by xiangma0510** [comment]
I found it, It seems that at the time I get the report the parameter pg_stat_statements.track_planning is disabled, I turned it on after
Thanks

**Comment by zubkov-andrei** [comment]
Have a nice day!
