### ISSUE TITLE
Сброс статистики pg_stat_statements

### ISSUE THREAD

**Issue by glushakov** [zubkov-andrei/pg_profile#25]
Андрей, здравствуйте!
Подскажите, есть ли возможность избежать сброса pg_stat_statements при каждом получении снимка (или в планах реализовать такой функционал), и собирать в виде дельты с предыдущим значением? Хочу использовать совместно с postgres_exporter, и опасаюсь, что частые сбросы испортят графики.

**Comment by zubkov-andrei** [comment]
Добрый день!
Да, это самый негативный момент в использовании pg_profile. Пока нет надёжного способа контролировать вымывание выражений из хэш-таблицы pg_stat_statements. В планах подобный функционал есть, но он требует незначительного изменения в pg_stat_statements. Пока патч на коммитфесте и судьба его еще неизвестна.
Однако, снимки pg_profile выполняются существенно реже запросов экспортёра, так что влияние они будут оказывать только на одно наблюдение из многих. Может это будет допустимо в вашей ситуации...

**Comment by glushakov** [comment]
Спасибо, буду пробовать!
