### ISSUE TITLE
Неожиданная проблема с отчетом (pg_statio_all_tables возвращает дубликаты)

### ISSUE THREAD

**Issue by sgrinko** [zubkov-andrei/pg_profile#28]
Проблема случайно вскрылась на одном из серверов.
При запуске SELECT profile.take_sample('сервер', false); вылезла ошибка:
```
ERROR: 23505: duplicate key value violates unique constraint "pk_last_stat_tables"
DETAIL: Key (server_id, sample_id, datid, relid)=(6, 1, 16419, 50936) already exists.
CONTEXT: SQL statement "INSERT INTO last_stat_tables(
...
PL/pgSQL function collect_obj_stats(jsonb,integer,integer,text,boolean,boolean) line 175 at SQL statement
PL/pgSQL function take_sample(integer,boolean) line 871 at assignment
PL/pgSQL function take_sample(name,boolean) line 9 at RETURN
SCHEMA NAME: profile
TABLE NAME: last_stat_tables
CONSTRAINT NAME: pk_last_stat_tables
LOCATION: _bt_check_unique, nbtinsert.c:670
```
При разборе этой ситуации я нашёл, что системное представление pg_statio_all_tables возвращает дубликаты для одной из моих таблиц. Стал разбираться в причинах и нашел, что связано это с невалидными индексами на toast таблице.
Такой невалидный индекс остался на таблице toast после упавшей команды REINDEX. В документации к команде (https://postgrespro.ru/docs/postgresql/14/sql-reindex#SQL-REINDEX-CONCURRENTLY) так и сказано, что такое может быть и нужно контролировать выполнение команды:

Если при перестроении индексов возникает проблема, например нарушение уникальности в уникальном индексе, REINDEX прерывается, но оставляет после себя «нерабочий» новый индекс в дополнение к уже существующему. Этот индекс будет игнорироваться запросами, так как он может быть неполным; тем не менее он будет обновляться при изменении данных, что повлечёт дополнительные издержки. Команда psql \d будет обозначать такой индекс как INVALID (нерабочий):

```
postgres=# \d tab
       Table "public.tab"
 Column |  Type   | Modifiers
--------+---------+-----------
 col    | integer |
Indexes:
    "idx" btree (col)
    "idx_ccnew" btree (col) INVALID
```

Если имя индекса с пометкой INVALID оканчивается на ccnew, это переходный индекс созданный при параллельной операции, и для исправления ситуации рекомендуется удалить его, выполнив DROP INDEX, а затем попытаться ещё раз выполнить REINDEX CONCURRENTLY. Если же имя нерабочего индекса оканчивается на ccold, значит, это исходный индекс, удалить который по какой-то причине не получилось. Такой индекс рекомендуется просто удалить, так как нужный индекс был перестроен успешно.

Таким образом запуск построения отчета помогу неявно в обнаружении "заблудшего" индекса на toast таблице :)

Я в данном вопросе хотел бы попросить тебя сообщить разработчикам (у тебя ведь есть прямые контакты с ними :) ) о такой проблеме с системным представлением. Сам по себе такой индекс не должен нарушать работу системного представления про которое сказано, что для одной таблицы возвращается строго 1 строка. (https://postgrespro.ru/docs/postgresql/14/monitoring-stats#MONITORING-PG-STATIO-ALL-TABLES-VIEW)

С другой стороны может быть есть смысл добавить временно защиту от такого и встроить доп.контроль на наличие таких невалидных индексов в БД?

Ведь наличие таких индексов ухудшает работу БД и неявно приводит к замедлению работы и увеличению IO. А поиск таких причин и есть как раз цель данного инструмента :)

**Comment by zubkov-andrei** [comment]
Сергей, добрый день!
Спасибо за детальное описание интрересного случая. Хоть оно к профайлу прямого отношения и не имеет, но как минимум требует расследования и учета в мониторинге. Я отпишусь по результатам. Думаю, этот случай найдёт свое отражение в mamonsu.

**Comment by sgrinko** [comment]
В версии mamonsu 3.2.0 внедрили метрику поиска невалидных индексов, поэтому теперь узнаем о такой возможной проблеме сразу же. Эту версию у себя уже внедрили.

Андрей, спасибо за содействие во внедрении этой метрики в mamonsu!

**Comment by zubkov-andrei** [comment]
Всегда пожалуйста!
Исходная проблема вызвана некорректным определением представления _pg_statio_all_tables_. По этому поводу я отправил патч в [hackers](https://www.postgresql.org/message-id/flat/acefef4189706971fc475f912c1afdab1c48d627.camel%40moonset.ru).
Вероятно, в отдалённом светлом будущем это будет поправлено в ваниле.
Что делать в этом смысле с профайлом я пока не решил. С одной стороны, можно рассчитывать на такое поведение представления и обрабатывать его не выпадая в ошибку, но с другой стороны - это некорректное поведение и правильное поведение профайла как раз и помогло обнаружить проблему.

**Comment by sgrinko** [comment]
Согласен, с тобой, что в pg_profile не надо вносить правок.
Как результат мы доработали mamonsu и ты отправил патч в hackers !
Так что будем считать проблему решённой.
Закрывай issue :) Спасибо!

**Comment by zubkov-andrei** [comment]
Пожалуйста! Закрываю :)
