### ISSUE TITLE
Проблема при работе от пользователя отличном от postgres

### ISSUE THREAD

**Issue by mgerasim** [zubkov-andrei/pg_profile#3]
При работе от пользователя отличном от postgres в операционной системы - не работает dblink, соответственно не создаются snapshots. 
Как вариант для решения проблемы явно указывать пользователя в dblink`ах. Пример реализации:
ч.1 https://github.com/mgerasim/pg_profile/commit/1435befe96abe895dc960200fc3627741106778e
ч.2 https://github.com/mgerasim/pg_profile/commit/7e2a47c9de9b3dc294b781d1dc8e2ee11deb7077

**Comment by zubkov-andrei** [comment]
В версии 0.0.6 добавлена возможность сбора статистик с нескольких инстансов Postgres, причем для каждой ноды можно установить свою строку соединения, которую будут использовать все dblink'и. Так что можно указать и пользователя и пароль, если не используются альтернативные способы авторизации.
