### ISSUE TITLE
Добавить функцию ручного удаления семплов сервера

### ISSUE THREAD

**Issue by xinferum** [zubkov-andrei/pg_profile#30]
Добрый день.

Есть предложение добавить в pg_profile функцию, которая позволяла бы удалять семплы конкретного сервера, не удаляя сам сервер. Сейчас есть только возможность ротации по времени хранения. Во время тестов потребовалось очистить все семплы конкретного сервера, сейчас это возможно только если сервер дропнуть и пересоздать.

Было бы удобно если бы функция позволяла удалять как определенные семплы (по id или за временной промежуток), так и сразу все семплы сервера.

Подобного функционала в документации и списке функций pg_profile не нашел.

**Comment by zubkov-andrei** [comment]
Добрый день!
Да такой функции нет. Написать ее несложно, но в ближайшем релизе не обещаю, поскольку я всё-таки его хочу сегодня выпустить.

**Comment by zubkov-andrei** [comment]
Несколько вариантов функции _delete_samples()_ добавлены а 4.0. Удалиять можно всё кроме снимков, входящих в baselines и последнего снимка, поскольку к нему привязаны данные, необходимые для расчета приращений в следующем снимке.

**Comment by xinferum** [comment]
Отлично. Спасибо!
