### ISSUE TITLE
Compatibility Matrix (pg_profile vs postgres)

### ISSUE THREAD

**Issue by PawelCzerwonka** [zubkov-andrei/pg_profile#32]
Hi,
Which version works with Postgresql 12,13 and 14? Can you create a matrix compatibility? e.g.
postgresql 14 | pg_profile 0.3.5 and higher
postgresql 13 | pg_profile 0.3.3 and higher
postgresql 12 | pg_profile 0.2.1 and higher

Thanks
P.

**Comment by zubkov-andrei** [comment]
Hi,
The most recent PostgreSQL 14 is supported since 0.3.4. Thank you, I'll add compatibility matrix in the docs in next release.
