### ISSUE TITLE
pg_stat_statements_reset() causes other tools to report from values

### ISSUE THREAD

**Issue by simonuwe** [zubkov-andrei/pg_profile#34]
You should mention in the docu, that the call of pg_stat_statements_reset()  could cause other monitoring tools to report wrong values, when a tools relies on increasing values in pg_stat_statements.

**Comment by zubkov-andrei** [comment]
Yes, I suppose it worth mentioning in the docs.

**Comment by zubkov-andrei** [comment]
Added a note in the docs for release 4.0
