### ISSUE TITLE
SELECT take_sample(); ISSUE

### ISSUE THREAD

**Issue by gael-efluid** [zubkov-andrei/pg_profile#37]
Hello,
After migrating my PG Instance from V13 to V14, I'm facing an issue when taking a sample :
![take_sample_issue](https://user-images.githubusercontent.com/83600500/167146918-ba9932c9-2a23-41ce-be71-36b94a781edb.PNG)

I checked and the table sample_statements is empty :
![image](https://user-images.githubusercontent.com/83600500/167147128-e31e7b75-bc84-4d9c-8166-ded80f780ff5.png)

Here are the extension on my instance :
![image](https://user-images.githubusercontent.com/83600500/167147216-3c490711-f639-45a7-9a39-15ef95d3053f.png)

I tried to DROP the EXTENSIONs related to pg_profile, then restart the instance, then reinstall them, but I still got the issue.

Do you have any idea on what's going on ?

Kind regards,
Gaël

**Comment by zubkov-andrei** [comment]
Hi, @gael-efluid 
I think it is a bug. I wonder that it is detected only now. It seems you've catched a query that can be executed as top-level query and as nested-level. And both are heavy enough to be saved in a sample. sample_statements PK is defined incorrectly and can't handle this. I'll fix it in next release.
Right now you can disable collection of nested-level statement statistics setting pg_stat_statements.track to 'top'. Ypu'll need to reset pg_stat_statements also.
Obviously you won't see nested-level statistics than. It only will be accounted in top-level statements.

**Comment by gael-efluid** [comment]
Hello,
I did your workaround and I can now take snapshots :)
Thanks a lot!

When do you think next release will be available ?

Kind regards,

**Comment by zubkov-andrei** [comment]
I think it should happen during a month or so...

Thank you for a report!

**Comment by zubkov-andrei** [comment]
Thanks again. Fix included in release 4.0
