### ISSUE TITLE
Support pg_stat_kcache version 2.2.1

### ISSUE THREAD

**Issue by portnov** [zubkov-andrei/pg_profile#39]
Similarly to #11, I just added '2.2.1' to collect_pg_stat_statements_stats, and it seems to work. Do you need a PR for this? :)

**Comment by zubkov-andrei** [comment]
Hi!
I'll change retention support in next version and it'll affect pg_stat_statements/kcache collection code. I'll add new kcache version support there. I think there is no need in PR.

**Comment by zubkov-andrei** [comment]
Release 4.0 should support pg_stat_kcache 2.2.1 correctly
