### ISSUE TITLE
Ошибка при установки расширения pg_profile 0.0.5 на PostgreSQL 9.3

### ISSUE THREAD

**Issue by vitabaks** [zubkov-andrei/pg_profile#4]
postgrestest=# CREATE EXTENSION pg_profile SCHEMA profile;
ERROR:  syntax error at or near "ON"
LINE 106: ...TO stmt_list VALUES (qres.queryid_md5,qres.query) ON CONFLIC...

**Comment by zubkov-andrei** [comment]
Уточните, пожалуйста, версию сервера postgresql. Похоже, что вы используете 9.4 или ниже. Там такой синтаксис был недопустим.

**Comment by vitabaks** [comment]
Так и есть. Версия 9.3.
Вы не планируете поддержку PostgreSQL 9.3/4?

**Comment by zubkov-andrei** [comment]
Версия устаревшая, так что задача не в приоритете, тем более что в этих версиях даже pg_stat_statements другое показывает (да еще и разное в 9.3 и 9.4). А что там в статистических представлениях еще даже и не смотрел. Так что в ближайшее время обещать ничего не могу.

**Comment by vitabaks** [comment]
Вас понял, спасибо.
