### ISSUE TITLE
Plugin compatibility with Postgres14?

### ISSUE THREAD

**Issue by kelkyip** [zubkov-andrei/pg_profile#47]
I have been using this plugin for my AWR postgres 11 report. I am trying to move to postgres 14 and just having trouble. Has anyone been using it for Postgres 14 or 13 ? If so, then I would know problem is on my end. thx

**Comment by zubkov-andrei** [comment]
Hi! There is at least one problem on Postgres 14, known as #37. It will be fixed in next release

**Comment by kelkyip** [comment]
thanks..

**Comment by zubkov-andrei** [comment]
Compatibility with Postgres 14 fixed in release 4.0
