### ISSUE TITLE
Вопрос по настройке таймаутов take_sample() в новой версии pg_profile 4.0

### ISSUE THREAD

**Issue by xinferum** [zubkov-andrei/pg_profile#48]
Добрый день.

Мы обновили у себя pg_profile с версии 0.3.6 до версии 4.0 сразу после его выхода.
По итогам чуть более недели использования у нас возникла такая ситуация, что каждый день довольно много раз pg_profile не может собрать данные во время запуска take_sample(). У нас используется выделенный сервер для сбора данных с разных баз, собираем данные каждый час.

Ошибок в выполнении take_sample() с точки зрения кода, нет в логе PostgreSQL мы видим только сообщения:
```
2022-09-02 00:00:00.074 MSK [1196()-3160] app=[],client=[] [LOG:  cron job 46 connection failed
2022-09-02 00:00:00.075 MSK [1196()-3161] app=[],client=[] [LOG:  cron job 47 connection failed
2022-09-02 00:00:00.075 MSK [1196()-3162] app=[],client=[] [LOG:  cron job 45 connection failed
```
В моменты когда для части серверов не удается получить семплы.

Я пробовал увеличить в функции take_sample(int4, bool) в 117 строке таймаут подключения dblink с 3 секунд до 30:
```
PERFORM dblink('server_connection','SET lock_timeout=30000');
```
Но это не улучшило ситуацию.

Подскажите, могу ли я где-то еще подкрутить таймауты, мы хотели бы получать семплы в большинстве случаев. Ранее на версии 0.3.6 у нас неудачные сборки были только когда базы были недоступны, а сейчас регулярно.
Проблема наблюдается независимо от того, когда выполняется take_sample() - вне окна сборки размеров отношений или в окне сборки размеров, у нас сборка отношений разрешена с 0 до 3 часов ночи по Москве, а проблемы со сборкой семплов возникают в течение всех суток.

**Comment by zubkov-andrei** [comment]
Добрый день!
Большое спасибо за сообщение, надо разбираться. К сожалению, по тексту ошибки понять что-либо трудно. Функция take_sample() должна возвращать текст ошибки, хорошо бы его получить. Самый просто вариант - выполнить вручную из psql и получить текст ошибки. Но если ошибка стабильно не воспроизводится, это может сразу не получиться. Тогда хорошо бы в задании, выполняемом по крону предусмотреть возможность сохранения результатов выполнения функции take_sample в какой-нибудь исторической таблице.

**Comment by xinferum** [comment]
Хорошо, обсудим с коллегой, что-нибудь придумаем для логирования. Или возможно просто попробуем погонять какую-нибудь реплику вызовами take_sample() раз в минуту на тестовом контуре, возможно поймаем момент воспроизведения проблемы.
Как будет новая информация - предоставлю логи.

**Comment by zubkov-andrei** [comment]
Проще всего наверное перенаправить вывод psql в файл с аппендом в задании крона.

**Comment by xinferum** [comment]
Добрый день.

С репликами стало чуть более понятно:
```
2022-09-05 09:00:34.016 MSK [19612()-8] app=[pg_cron],client=[::1(44426)] [profile_mon@profile_mon], [vxid:8/3139 txid:2291307] [SELECT] ERROR:  FATAL:  terminating connection due to conflict with recovery
    DETAIL:  User query might have needed to see row versions that must be removed.
    HINT:  In a moment you should be able to reconnect to the database and repeat your command.
    server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```
Сбор данных иногда сталкивается с тем, что его прерывает postgresql для наката изменений с мастера. Ранее такого не наблюдали, возможно сбор статистик стал дольше, хотя на нагруженном кластере take_sample() занимает порядка 6 секунд.

Может быть были добавлены какие-то данные статистики сервера, которые прилетают с мастера и теперь встречается такое поведение?

По мастерам пока ошибку не отловил, но take_sample() там несколько раз за день отваливается.

**Comment by zubkov-andrei** [comment]
Спасибо за информацию. Это интересно. В 4-й версии сбор статистик происходит (наконец) в режиме изоляции REPEATABLE READ READ ONLY, что, безусловно, увеличивает вероятность получения такой ошибки на реплике.
Что тут можно попробовать...

- Попытаться использовать механизмы разрешения конфликтов репликации, используя [max_standby_streaming_delay](https://www.postgresql.org/docs/15/runtime-config-replication.html#GUC-MAX-STANDBY-STREAMING-DELAY) или [hot_standby_feedback](https://www.postgresql.org/docs/15/runtime-config-replication.html#GUC-HOT-STANDBY-FEEDBACK). Понимая при этом все плюсы и минусы этих решений.
- Подумать о сбросе уровня изоляции в pg_profile, но это не решит проблему полностью, поскольку теоретически на такое можно нарваться и на уровне одного выражения.

**Comment by xinferum** [comment]
После разнесения заданий take_sample() во времени по пачкам серверов, проблема ушла. Ошибок сборки семплов даже на репликах не было со вчерашнего вечера. Мы сделали пачки серверов еще меньше (с 10 до 5 серверов за раз уменьшили) сейчас, разнесены пачки с шагом в 2 минуты.

В логе PostgreSQL сообщения о блокировках ShareUpdateExclusiveLock так и остались, но сейчас очередь меньше получается и в таймауты укладываемся.
Может в коде pg_profile попробовать использовать рекомендательные блокировки pg_advisory_lock() ?

**Comment by zubkov-andrei** [comment]
Спасибо за информацию. Это должно помочь в размышлениях. advisory_lock там уже был, но тут он не очень нужен. Сейчас профайл блокирует возможность запуска двух параллельных снимков по одному серверу используя блокировку уровня записи каждом сервере. Но, похоже, не очень получается. Я подумаю что с этим можно сделать, тут нужно несколько методов попробовать.

**Comment by zubkov-andrei** [comment]
Сергей, а будет у вас возможность проверить тестовую версию?
С ней будет сложность - на нее нельзя будет обновиться и с нее потом не вернешься обновлением на релизную версию - только удалять и заново ставить. Учитывая необходимость сброса статистик stat_statements, информацию о нагрузке, собранную за время тестирования вы потеряете если только не сохраните на некоторое время тестовую версию после окончания тестирования, но тогда отчеты за это время можно будет собрать только в ней.

**Comment by xinferum** [comment]
Мы можем потерять определенный период данных на время тестов.
Текущее состояние кластера забекапим (может даже просто на холодную, остановив postgresql), а потом вернемся на него, вернув файлы расширения обратно версии 4.0.

Я только не понял момента с тем что на тестовую версию нельзя обновиться. То есть все настраивать с нуля придется для тестов на бд профайла? Лучше бы конечно чтобы с 4.0 я мог обновится на текстовую версию, пусть это и будет путь в один конец и ничего потом с ней нельзя будет сделать.

**Comment by zubkov-andrei** [comment]
Обновление на тестовую версию может получиться, а может и нет - зависеть будет от трудоёмкости составления скрипта обновления. Но в самом крайнем случае настройки серверов в профайле хранятся в одной таблице - можно и перегрузить. И не думаю что вам понадобится бэкап - можно просто создать копию базы данных и опыты вести в ней, а потом просто дропнуть.

**Comment by zubkov-andrei** [comment]
Сегрей, я отправил новую версию в ветку develop. В числе прочего, в ней должна быть поправлена и обнаруженная вами проблема. Если вас не затруднит, посмотрите работает ли она как ожидается. Если всё будет хорошо, я выпущу из этой ветки релиз.

**Comment by xinferum** [comment]
Андрей, я обновил pg_profile, перевел обратно запуск сбора данных со всех серверов одновременно в 00 минут каждого часа.
Уже дважды был сбор данных, серверов по которым не было семплов наш мониторинг пока не обнаружил. Из лога сервера пропали сообщения о блокировках ShareUpdateExclusiveLock.

Похоже проблема исправлена.

Я предлагаю пока несколько дней пусть покрутится новая версия, например до среды (чтобы и нагрузка выходных была на базах и пары будних дней), а в среду я напишу по итогу все ли было нормально. Если время терпит.

**Comment by zubkov-andrei** [comment]
Большое спасибо, Сергей. Да, конечно, в этом деле торопиться не надо. С 4.0 нехорошо получилось именно из-за невозможности полноценно протестировать в такой развесистой конфигурации и на протяжении продолжительного времени. Хорошо бы еще убедиться и в том что отчёты нормально строятся, но тут я особых проблем не ожидаю. Буду ждать от вас сообщения о результатах наблюдений.

**Comment by zubkov-andrei** [comment]
Сергей, добрый день.
Большое спасибо за обнаруженную проблему и тщательное тестирование. Думаю, сегодня-завтра я опубликую релизную версию 4.1. Я планирую ее публикацию из версии, которую вы тестировали, так что никаких проблем с дальнейшим обновлением у вас не должно быть.

**Comment by xinferum** [comment]
Отлично! Спасибо большое за разработку решения! Issue закрываю.
