### ISSUE TITLE
GPL 

### ISSUE THREAD

**Issue by yogi-learns** [zubkov-andrei/pg_profile#53]
Hi Andrei,

I like pg_profile, and would like to use it in our postgres database in our org. Can I request you to please include GPLicence in your code? That way our sec team wont mind us using it.

Regards
Yogi

**Comment by zubkov-andrei** [comment]
Hello, Yogi!

Thank you for your attention to pg_profile!
I'm a little bit puzzled with your question. pg_profile is released under Postgres license to be fully compatible with the DBMS. I don't understand how do your security team allows using PostgreSQL under Postgres license and avoids using pg_profile with exact the same licence?

**Comment by yogi-learns** [comment]
Thanks for replying, Andrei.

I later searched your disclaimer, and found it matching MIT license completely.
I guess, I was just looking for a mention of the MIT license in the disclaimer(license file). 
Just seeing that 3 letter acronym would shut off any and all questions our sec team might have. 

You know how silly these things can be. I got to know, should we really get into approval process in my org, it ll delay my deployment for more than a month. 

So if you could just say, something like... "free to use under MIT license". This can save me a month of BS to handle. :-p

-Yogi

**Comment by zubkov-andrei** [comment]
I've got your point, Yogi

Let's try to add some more compatibility with PostgreSQL license.. How about such contents of LICENSE file?
```
pg_profile extension is released under the PostgreSQL License, a liberal Open Source license, similar to the BSD or MIT licenses.

pg_profile - Postgres historic workload reporting tool

Copyright (c) 2017-2022 Andrei Zubkov

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose, without fee, and without a written agreement
is hereby granted, provided that the above copyright notice and this
paragraph and the following two paragraphs appear in all copies.

IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR DIRECT,
INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND
THE COPYRIGHT HOLDER HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT,
UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
```
I think you should ask your sec team about it.

**Comment by yogi-learns** [comment]
This looks good to me. I ll check with my sec team though.

Thanks a ton for taking out time to do this.

- Yogi

**Comment by yogi-learns** [comment]
Hi Andrei,

I checked with team. This is acceptable to them.

Kindly update same in the license file.

Thanks again for your support.

-  Yogi

**Comment by zubkov-andrei** [comment]
Hi, Yogi,

I've updated the LICENSE file as we discussed above. I think the issue can be closed when your sec team will approve using pg_profile in your environment.

Regards, Andrei Zubkov

**Comment by yogi-learns** [comment]
Thank you, Andrei.
I ll keep you posted.

- Yogi
