### ISSUE TITLE
README.md not reflecting correct link for Example Reports

### ISSUE THREAD

**Issue by shane-borden** [zubkov-andrei/pg_profile#61]
The following 2 links need to be updated to reflect the Postgres 15:

From:
[Regular report from Postgres 14 database](https://zubkov-andrei.github.io/pg_profile/report_examples/pg14.html)
[Differential report from Postgres 14 database](https://zubkov-andrei.github.io/pg_profile/report_examples/pg14_diff.html)

To:
[Regular report from Postgres 15 database](https://zubkov-andrei.github.io/pg_profile/report_examples/pg15.html)
https://zubkov-andrei.github.io/pg_profile/report_examples/pg15.html
[Differential report from Postgres 15 database](https://zubkov-andrei.github.io/pg_profile/report_examples/pg15_diff.html)
https://zubkov-andrei.github.io/pg_profile/report_examples/pg15_diff.html

**Comment by zubkov-andrei** [comment]
README.md updated
