### ISSUE TITLE
Возвращать подробности об ошибке в случае провала вызова take_sample(server name [, skip_sizes boolean]) 

### ISSUE THREAD

**Issue by monok0** [zubkov-andrei/pg_profile#66]
Сейчас функция take_sample() в случае возникновения ошибки возвращает подробности о ней, в то время как функция take_sample(server name [, skip_sizes boolean]) возвращает только 0 или 1 в случае успеха и неудачи соответственно. Хотелось бы иметь возможность получить информацию о возникшей проблеме аналогично take_sample().

**Comment by zubkov-andrei** [comment]
Добрый день! Да есть такая проблема. Как-нибудь сделаю такую возможность.

**Comment by zubkov-andrei** [comment]
Реализовано в 4.2
