### ISSUE TITLE
Не работает статистика pg_stat_kcache

### ISSUE THREAD

**Issue by dtyugaev** [zubkov-andrei/pg_profile#68]
PostgreSQL 13.11
pg_profile 4.1
pg_stat_kcache 2.2.1

при создании отчета не создается раздел со статистикой pg_stat_kcache

**Comment by zubkov-andrei** [comment]
Добрый день!
Тут что-то не так, должно работать. Покажите \dx, shared_preload_libraries.

**Comment by fahrenheit314** [comment]
Добрый день!
Такая же ситуация, расширение установлено, но в отчете статистики не появляются. 
Никак не могу понять в чем проблема. 

Вывод \dx

| Name                 | Version | Schema     | Description                                                        |
|----------------------|---------|------------|--------------------------------------------------------------------|
| dblink               | 1.2     | public     | connect to other PostgreSQL databases from within a database       |
| lo                   | 1.1     | public     | Large Object maintenance                                           |
| pg_profile           | 4.8     | profile    | PostgreSQL load profile repository and report builder              |
| pg_stat_kcache       | 2.3.1   | public     | Kernel statistics gathering                                        |
| pg_stat_statements   | 1.10    | public     | track execution statistics of all SQL statements executed          |
| pg_trgm              | 1.6     | public     | text similarity measurement and index searching based on trigrams  |
| pg_wait_sampling     | 1.1     | public     | sampling based statistics of wait events                           |
| pgstattuple          | 1.5     | public     | show tuple-level statistics                                        |
| plpgsql              | 1.0     | pg_catalog | PL/pgSQL procedural language                                       |
| uuid-ossp            | 1.1     | public     | generate universally unique identifiers (UUIDs)                    |

shared_preload_libraries
----------------------------------------------------
 pg_stat_statements,pg_wait_sampling,pg_stat_kcache
