### ISSUE TITLE
Как очищается таблица last_stat_statements?

### ISSUE THREAD

**Issue by triwada** [zubkov-andrei/pg_profile#71]
Добрый день, есть проблема с большим размером таблицы last_stat_statements (на текущий момент 12 ГБ).
Значение max_sample_age стояло 90 дней, в таблице хранились данные за 60 дней.

Установил max_sample_age в 45 дней, затем выполнил take_sample() и vacuum full, но размер таблицы last_stat_statements не уменьшился.
Установил max_sample_age в 15 дней, затем выполнил take_sample() и vacuum full, но размер таблицы last_stat_statements не уменьшился.

В чём может быть проблема?

версия pgpro_pwr 4.0

**Comment by zubkov-andrei** [comment]
Прошу прощения за поздний ответ...
В 4.0 была бага, поправленная в 4.1 Попробуйте обновиться и сделать vacuum full после этого.

**Comment by triwada** [comment]
обновление выполнил, но пару недель назад  пришлось выполнить truncate.
Если повторится и с новой версией 4.1.3, то заново открою этот issue.
