### ISSUE TITLE
report is empty

### ISSUE THREAD

**Issue by herwigg** [zubkov-andrei/pg_profile#76]
Hi, installation of pg_profile is ok, creating of a local and test server is ok, I scheduled every half hout to take a sample, that is working fine. But when I try to view   a report is is almost empty: it just contains a header and a lot of spaces or hyphen or underscore characters. This is a report for the last 24 hours on a Postgres version 15 instance. 
Postgres profile report (6 -43)
pg_profile version 4.2

Server name: PTC13

Monitoring for PTC13

Report interval: 2023-09-26 15:26:04+02 - 2023-09-27 13:30:01+02

Report sections

any ideas what could cause these (empty) reports ?

**Comment by zubkov-andrei** [comment]
Hi! What exact command did you use to create an .html file of a report?

**Comment by herwigg** [comment]
Hi, I did psql ...  -c "select get_report('PTC13',tstzrange(now() - interval '1 day',now()))" -o last24h_report.html

**Comment by zubkov-andrei** [comment]
Are there '-Aqt' keys in your command (behind the '...')?

**Comment by herwigg** [comment]
no, there were not, I added these and now there is something in it. sorry it was stupid.

**Comment by zubkov-andrei** [comment]
Good!
