### ISSUE TITLE
I encountered a problem when deploying

### ISSUE THREAD

**Issue by dashu96** [zubkov-andrei/pg_profile#81]
Hello:
Thank you for providing excellent open source tools, but I encountered some problems when deploying.
![截图20231204164904_1](https://github.com/zubkov-andrei/pg_profile/assets/45221486/1073ee0c-edf0-448b-857c-8ef9e65bc72b)

I read other posts and noticed that you might be caused by not finding the server_name, but I designated the correct server_name still unable to execute the function command.
<img width="734" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/c6f67b64-c8a3-4a11-bc38-7fe50a912c9d">
Looking forward to your reply, thank you!

**Comment by dashu96** [comment]
Thank you for your answer. In fact, I can generate the report. I actually reported an error when I executed SELECT * FROM take_sample ('local') under the postgres database, and I also reported an error when I executed dblink_connect. This should have nothing to do with the pg_hba file, I am using pofile_mon users can log in directly. I am\ c switch to the test database and install the plug-in and then execute the take_sample function and generate the report smoothly. But the dblink_connect function still doesn't work.

**Comment by dashu96** [comment]
我还有一个问题，我看到说明文档有个track_functions = all/pl参数请问 “all/pl” 是一个整体的值吗，还是“all” or "pl"两个值选择一个，我尝试把“all/pl”当成一个值，数据库无法启动。

**Comment by dashu96** [comment]
I have another question. I see that there is a track_function in the description document. Is "all/pl" a overall value, or "all" or "pl" to choose one. I try to put "ALL/PL "is used as a value, and the database cannot start.

**Comment by zubkov-andrei** [comment]
pg_profile won't work without the ability to connect over dblink. The initial error message means that dblink can't connect in the unix domain socket /tmp/.s.PGSQL.2008. Does this file exist?
Postgres connection can be established over the network socket or over unix domain socket. Each type of connection handled differently in pg_hba.conf file ('host' and 'local' entries respectively).

Can you connect to all databases of your cluster by user profile_mon user by psql? What exact command do you use?

**Comment by dashu96** [comment]
Select dblink_connect ('dbname = postgres port = 2008 user = propile_mon password = pwd_mon'); The reason for executing this function is found because Port, I should use my own database port.

But I encountered a new problem. I reinstalled the database to perform step by step according to the tutorial. When the function executed this function, the selection propile.snapshot () reported an error.
<img width="1280" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/dcef11cb-2dd4-4b2e-b652-9c9a5506f3ae">
<img width="824" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/2f30aef6-9fcf-4beb-8cd6-34fcae98725c">
<img width="618" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/63ee7656-3e9a-4c78-b4ba-801311d38853">
<img width="1280" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/702325f6-bbed-49e3-a96b-7130be0112a6">

**Comment by dashu96** [comment]
I used two ways to install the above. There is no installation of PG_WAIT_SAMPLING and PG_STAT_KCACHE plug -ins. This two plug -ins has no authority.
<img width="880" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/2575d4e8-b6c7-4170-a841-460e94d2032b">
<img width="796" alt="image" src="https://github.com/zubkov-andrei/pg_profile/assets/45221486/01e2a15c-d8dd-4996-a982-8e8f23c96078">
I do n’t know if it is my reference tutorial. I compared with the documents in DOC, it is not significantly different.Is it my step?It is strange why switching from the Postgres database to the test database in the morning can be used normally.It's really puzzling.

**Comment by dashu96** [comment]
If you want to say that there is anything different, it is still track_functions = all/pl of this parameter. I set it if all cannot start the database
