### ISSUE TITLE
rpeort filled with blank character

### ISSUE THREAD

**Issue by gael-efluid** [zubkov-andrei/pg_profile#83]
Hello,
I don't get why, but since few days the reports generated are really heavy (> 500Mo) and they are filled with blank character
![image](https://github.com/zubkov-andrei/pg_profile/assets/83600500/8d689544-db9c-4bed-9e02-ad4565880ee9)

Any idea on what's is going on ?

[pgprofile_TP2_efluid_e2c.zip](https://github.com/zubkov-andrei/pg_profile/files/13740536/pgprofile_TP2_efluid_e2c.zip)

**Comment by zubkov-andrei** [comment]
Maybe it is caused by incorrect command parameters used for report generation causing psql formatting. If psql is used, there should be -Aqt flags. Check the exact command noted in the docs:
```
psql -Aqtc "SELECT profile.get_report(480,482)" -o report_480_482.html
```
Just substitute you sample_id numbers there.

**Comment by gael-efluid** [comment]
Indeed, with the A parameter there is no blank in the report.
I never used this parameter before, so I don't get why I faced thi issue just now... 
Anyway, thanks for the help !
