### ISSUE TITLE
В отчете не верный размер бд.

### ISSUE THREAD

**Issue by Guzya** [zubkov-andrei/pg_profile#9]
Здравствуйте!
Заметили, что в отчете не верно указан размер бд (больше).
И чем больше период отчета, тем больше указывается размер.

В таблице profile.sample_stat_database  в  поле datsize размер правильный.

**Comment by Guzya** [comment]
Проблема по всей видимости в функции dbstats(), там поле datsize суммируется, хотя должен проставляться размер из последнего снимка.
sum(datsize)::bigint AS datsize,

**Comment by zubkov-andrei** [comment]
Большое спасибо - такие ошибки сложно все сразу выловить, и тестирование на все поля отчета не повесишь...
При ближайшей возможности поправлю и выпущу релиз.

**Comment by Guzya** [comment]
Спасибо!
